return {
    {
        "nvim-telescope/telescope.nvim",
        branch = "0.1.x",
        dependencies = { "nvim-lua/plenary.nvim" },
        cmd = "Telescope",
        keys = {
            { "<leader>fb", function() require("telescope.builtin").buffers() end },
            { "<leader>ff", function() require("telescope.builtin").find_files() end },
            { "<leader>fF", function() require("telescope.builtin").git_files() end },
            { "<leader>fr", function() require("telescope.builtin").oldfiles() end },
            { "<leader>ft", function() require("telescope.builtin").filetypes() end },
            { "<leader>gb", function() require("telescope.builtin").git_branches() end },
            { "<leader>gc", function() require("telescope.builtin").git_bcommits() end },
            { "<leader>gC", function() require("telescope.builtin").git_commits() end },
            { "<leader>gs", function() require("telescope.builtin").git_status() end },
            { "<leader>gS", function() require("telescope.builtin").git_stash() end },
            { "<leader>sb", function() require("telescope.builtin").current_buffer_fuzzy_find() end },
            { "<leader>sc", function() require("telescope.builtin").command_history() end },
            { "<leader>sC", function() require("telescope.builtin").commands() end },
            { "<leader>sd", function() require("telescope.builtin").lsp_definitions() end },
            { "<leader>sg", function() require("telescope.builtin").live_grep() end },
            { "<leader>sh", function() require("telescope.builtin").help_tags() end },
            { "<leader>sH", function() require("telescope.builtin").search_history() end },
            { "<leader>si", function() require("telescope.builtin").lsp_implementations() end },
            { "<leader>sm", function() require("telescope.builtin").marks() end },
            { "<leader>sM", function() require("telescope.builtin").man_pages() end },
            { "<leader>so", function() require("telescope.builtin").vim_options() end },
            { "<leader>sr", function() require("telescope.builtin").lsp_references() end },
            { "<leader>sR", function() require("telescope.builtin").registers() end },
            { "<leader>ss", function() require("telescope.builtin").lsp_document_symbols() end },
            { "<leader>sS", function() require("telescope.builtin").lsp_workspace_symbols() end },
            { "<leader>sw", function() require("telescope.builtin").grep_string() end },
            { "<leader>s`", function() require("telescope.builtin").resume() end },
        },
        opts = {
            pickers = {
                man_pages = {
                    sections = { "ALL" },
                },
            },
        },
    },
}
